In [89]:
import numpy as np

# méthodes ndarray

In [90]:
np.random.seed(0)
A = np.random.randint(0, 10, [5, 5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [91]:
A.sum()

135

axis = 0 représente l'axe des  colonnes<br/>
axis = 1 représente l'axe des lignes<br/>
peut être utilisé avec toutes les méthodes ci-dessous

In [92]:
A.sum(axis=0) #axis = 0 provoque la somme des colonnes

array([32, 25, 31, 30, 17])

In [93]:
A.sum(axis=1) #axis = & provoque la somme des lignes

array([18, 23, 30, 29, 35])

In [94]:
A.cumsum() #somme cumulée

array([  5,   5,   8,  11,  18,  27,  30,  35,  37,  41,  48,  54,  62,
        70,  71,  77,  84,  91,  99, 100, 105, 114, 122, 131, 135])

In [95]:
A.cumsum(axis=0)

array([[ 5,  0,  3,  3,  7],
       [14,  3,  8,  5, 11],
       [21,  9, 16, 13, 12],
       [27, 16, 23, 21, 13],
       [32, 25, 31, 30, 17]])

In [96]:
A.cumsum(axis=1)

array([[ 5,  5,  8, 11, 18],
       [ 9, 12, 17, 19, 23],
       [ 7, 13, 21, 29, 30],
       [ 6, 13, 20, 28, 29],
       [ 5, 14, 22, 31, 35]])

In [97]:
A.prod() #produit
A.cumprod() #produit cumulé

array([5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [98]:
A.min(axis=1)

array([0, 2, 1, 1, 4])

In [99]:
A.argmin(axis=0) #index de la valeur la plus faible, car 3 est sur la deuxième ligne donc 1 et 0 et 3 sont sur 
#la première ligne

array([0, 0, 0, 1, 2], dtype=int64)

In [100]:
#A.sort() #range les valeurs par ordre croisant par défaut sur la ligne

# méthodes mathématiques de numpy

pour accéder aux fonctions mathématiques np.nom_fonction(valor)

In [101]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01, 2.00855369e+01,
        1.09663316e+03],
       [8.10308393e+03, 2.00855369e+01, 1.48413159e+02, 7.38905610e+00,
        5.45981500e+01],
       [1.09663316e+03, 4.03428793e+02, 2.98095799e+03, 2.98095799e+03,
        2.71828183e+00],
       [4.03428793e+02, 1.09663316e+03, 1.09663316e+03, 2.98095799e+03,
        2.71828183e+00],
       [1.48413159e+02, 8.10308393e+03, 2.98095799e+03, 8.10308393e+03,
        5.45981500e+01]])

# les statistiques avec numpy

In [102]:
A.mean(axis=0) #moyenne

array([6.4, 5. , 6.2, 6. , 3.4])

In [103]:
A.std() #écart-type

2.6683328128252666

In [104]:
A.var() #variance

7.12

## méthodes pour les statistiques

In [105]:
np.corrcoef(A)[0, 1] #coefficient de correlation 
# [0, 1] permet d'accéder à la valeur

0.39741306906256163

In [115]:
values, counts = np.unique(A, return_counts=True) #renvoie le nombre fois qu'une valeur se répète
counts_arg = counts.argsort()
print(counts)
print(values)
print(counts_arg)

[1 2 1 3 2 3 2 4 4 3]
[0 1 2 3 4 5 6 7 8 9]
[0 2 1 4 6 3 5 9 7 8]


In [112]:
values_sort = values[counts_arg]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [118]:
for i, j in zip(counts_arg, counts[counts_arg]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4
