In [435]:
import numpy as np

# Statistiques

## méthodes ndarray

In [436]:
np.random.seed(0)
A = np.random.randint(0, 10, [3, 3])
A

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [437]:
A.sum()

37

axis = 0 représente l'axe des  colonnes<br/>
axis = 1 représente l'axe des lignes<br/>
peut être utilisé avec toutes les méthodes ci-dessous

In [438]:
A.sum(axis=0) #axis = 0 provoque la somme des colonnes

array([11, 12, 14])

In [439]:
A.sum(axis=1) #axis = & provoque la somme des lignes

array([ 8, 19, 10])

In [440]:
A.cumsum() #somme cumulée

array([ 5,  5,  8, 11, 18, 27, 30, 35, 37])

In [441]:
A.cumsum(axis=0)

array([[ 5,  0,  3],
       [ 8,  7, 12],
       [11, 12, 14]])

In [410]:
A.cumsum(axis=1)

array([[ 5,  5,  8],
       [ 3, 10, 19],
       [ 3,  8, 10]])

In [411]:
A.prod() #produit
A.cumprod() #produit cumulé

array([5, 0, 0, 0, 0, 0, 0, 0, 0])

In [412]:
A.min(axis=1)

array([0, 3, 2])

In [413]:
A.argmin(axis=0) #index de la valeur la plus faible, car 3 est sur la deuxième ligne donc 1 et 0 et 3 sont sur 
#la première ligne

array([1, 0, 2], dtype=int64)

In [414]:
A.sort() #range les valeurs par ordre croisant par défaut sur la ligne

## méthodes mathématiques de numpy

pour accéder aux fonctions mathématiques np.nom_fonction(valor)

In [415]:
np.exp(A)

array([[1.00000000e+00, 2.00855369e+01, 1.48413159e+02],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03],
       [7.38905610e+00, 2.00855369e+01, 1.48413159e+02]])

## les statistiques avec numpy

In [416]:
A.mean(axis=0) #moyenne

array([1.66666667, 4.33333333, 6.33333333])

In [417]:
A.std() #écart-type

2.5579698740491863

In [418]:
A.var() #variance

6.54320987654321

### méthodes pour les statistiques

In [419]:
np.corrcoef(A)[0, 1] #coefficient de correlation 
# [0, 1] permet d'accéder à la valeur

0.9971764649527378

In [420]:
print(A)
values, counts = np.unique(A, return_counts=True) #renvoie le nombre fois qu'une valeur se répète
counts_arg = counts.argsort() #renvoie des index en fonction d'une nombre de fois où le chiffre apparait
print(values)
print(counts)
print(counts_arg)

[[0 3 5]
 [3 7 9]
 [2 3 5]]
[0 2 3 5 7 9]
[1 1 3 2 1 1]
[0 1 4 5 3 2]


In [421]:
values_sort = values[counts_arg]
values_sort

array([0, 2, 7, 9, 5, 3])

In [422]:
for i, j in zip(values_sort, counts[counts_arg]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 7 apparait 1
valeur 9 apparait 1
valeur 5 apparait 2
valeur 3 apparait 3


# présence de valeurs qui ne sont pas des nombres

In [423]:
A = np.random.randn(5, 5)
A[0, 2] = np.nan
A[4, 3] = np.nan
A

array([[ 0.95008842, -0.15135721,         nan,  0.4105985 ,  0.14404357],
       [ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,         nan,  0.15494743]])

In [424]:
A.mean()

nan

In [425]:
np.nanmean(A) #dans numpy, il existe des méthodes qui permettent d'ignorer les NaN

0.25219043815520814

In [426]:
np.isnan(A).sum()/A.size #isnan() crée un tableau de booléans, sum permet de compter le nb de fois que True apparait.

0.08

In [427]:
A[np.isnan(A)] = 0 #remplace les NaN par zéro en utilisant le masque de bool
A

array([[ 0.95008842, -0.15135721,  0.        ,  0.4105985 ,  0.14404357],
       [ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  0.        ,  0.15494743]])

# Algèbre Linéaire

In [428]:
A = np.ones((2, 3))
B = np.ones((3, 2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [429]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [430]:
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [431]:
A.T.shape

(3, 2)

In [432]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [433]:
A = np.random.randint(0, 10, [3, 3])
A

array([[8, 1, 1],
       [7, 9, 9],
       [3, 6, 7]])

In [434]:
np.linalg.det(A) #calcul du déterminant qui doit être différent de zéro

64.99999999999999

In [443]:
np.linalg.pinv(A)

array([[ 0.17919075, -0.0867052 ,  0.12138728],
       [-0.12138728, -0.00578035,  0.20809249],
       [ 0.03468208,  0.14450867, -0.20231214]])

## Calcul des vecteurs

In [396]:
valeurs_propres, vecteurs_propres = np.linalg.eig(A)
print(valeurs_propres)
print(vecteurs_propres)

[16.57403508  6.85375335  0.57221157]
[[ 0.16010971  0.77315719  0.00700444]
 [ 0.8130696  -0.37409563 -0.73262449]
 [ 0.55971664 -0.5121332   0.68059701]]


### Exercice <br/>
Standartiser la matrice A sur chaque colonne

In [444]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [445]:
D = (A - A.mean(axis=0)) / A.std(axis=0)
D

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])