### NumPy

In [8]:
import numpy as np

In [9]:
A = np.array([[1, 2], [3, 6]])
B = np.array([[2, 1], [4, 3]])

In [10]:
A.ndim #inddique sont nombre de dimension

2

In [11]:
A.shape #renvoie la taille de la matrice => donne un tumple, accès aux données mais peut pas les modifier.

(2, 2)

In [12]:
A.size #indique le nombre de valeur dans le tableau

4

In [13]:
A + B

array([[3, 3],
       [7, 9]])

In [14]:
A - B

array([[-1,  1],
       [-1,  3]])

In [15]:
A.dot(B)

array([[10,  7],
       [30, 21]])

In [16]:
A.T #renvoie la transposer de la matrice

array([[1, 3],
       [2, 6]])

In [31]:
#C = np.hstack((A, B)) #fusionne les tableaux de manière horizontale
C= np.concatenate((A, B), axis=1) #recommandé
C

array([[1, 2, 2, 1],
       [3, 6, 4, 3]])

In [33]:
#D = np.vstack((A, B)) #fusionnne les tableaux de manière verticale
D = np.concatenate((A, B), axis=0)
D

array([[1, 2],
       [3, 6],
       [2, 1],
       [4, 3]])

In [41]:
D = D.reshape((2, 4)) #reréparti les données et permet de rajouter une dimension à un tableau à une dimension
D

array([[1, 2, 3, 6],
       [2, 1, 4, 3]])

In [44]:
D = D.ravel()
D

array([1, 2, 3, 6, 2, 1, 4, 3])

In [17]:
np.array([[n + m for n in range(3)] for m in range(3)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [18]:
np.arange(0, 10, 1) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0, 10, 25) #crée un tableau allant de 0 à 10 comprennant 25 valeurs espacées régulièrement.

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [20]:
np.logspace(0, 10, 10, base=np.e) #crée un tableau de 10 valeurs par par rapport à une fonction

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [21]:
from numpy import random

In [22]:
random.rand(5,5) #crée une matrice de valeur aléatoire de taille 5 x 5

array([[0.88239254, 0.36086665, 0.92113033, 0.4784419 , 0.81737119],
       [0.2047694 , 0.62901884, 0.68251129, 0.43194261, 0.66153267],
       [0.18007865, 0.12090281, 0.96628805, 0.14489283, 0.16913751],
       [0.55446579, 0.78392939, 0.28004952, 0.76696905, 0.41783445],
       [0.38332826, 0.01102708, 0.97312993, 0.85904227, 0.21442581]])

In [23]:
np.diag([1,2,3,4]) #crée un tableau avec un diagonal des numéros précisés

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
np.zeros((3,3)) #crée un tableau uniquement de zéro

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((3 ,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
M = random.randn(3,3)
M

array([[ 1.69873259,  1.84458814, -0.62269969],
       [ 0.22179152, -0.85336106,  0.44766404],
       [-1.63932143,  0.60015443,  0.83214789]])

In [135]:
M[0,1] #renvoie la valeur à la ligne 0 et colonne 1

0.6192032376105315

In [136]:
M[1] #renvoie les valeur de la ligne 1

array([0.99254943, 0.28230955, 0.8876356 ])

In [137]:
M[1,:] #renvoie les valeur de la ligne 1

array([0.99254943, 0.28230955, 0.8876356 ])

In [138]:
M[:,1] #renvoie les valeurs de la colonne 1

array([0.61920324, 0.28230955, 0.76159591])

In [48]:
N = M[0:2 , 0:2] #sélectionne une partie du tableau
N

array([[ 1.69873259,  1.84458814],
       [ 0.22179152, -0.85336106]])

In [59]:
P = np.zeros((4, 4))
P

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
P[1:3, 1:3] = 1
P

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [64]:
Q = np.zeros((5, 5))
Q

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
Q[::2, ::2] = 1
Q

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [55]:
M[:, -2:]

array([[ 1.84458814, -0.62269969],
       [-0.85336106,  0.44766404],
       [ 0.60015443,  0.83214789]])

In [139]:
M[0, 0] = 1 # assigne une nouvelle valeur à la position souhaitée
M

array([[1.        , 0.61920324, 0.36332481],
       [0.99254943, 0.28230955, 0.8876356 ],
       [0.92092024, 0.76159591, 0.46375722]])

In [140]:
M[1,:] = 0 #assigne une nouvelle valeur à une ligne
M

array([[1.        , 0.61920324, 0.36332481],
       [0.        , 0.        , 0.        ],
       [0.92092024, 0.76159591, 0.46375722]])

In [95]:
M[:,1] = 2 #assigne une nouvelle valeur à une colonne
M

array([[1.        , 2.        , 0.12853519],
       [0.        , 2.        , 0.        ],
       [0.4066289 , 2.        , 0.52956286]])

In [69]:
x = np.arange(0, 10 , 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [70]:
mask = (5 < x) * (x < 7.5) #crée un masque sur les données
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [71]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [73]:
x[mask] = 100
x

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. , 100. , 100. , 100. , 100. ,   7.5,   8. ,   8.5,
         9. ,   9.5])

In [151]:
index = np.where(mask) #indique les index qui respecte les conditions
index

(array([11, 12, 13, 14], dtype=int64),)

In [152]:
x[index]

array([5.5, 6. , 6.5, 7. ])

In [155]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [157]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

In [170]:
v = np.arange(0, 10, 2)
row_index = [1, 2 ,4]
v[row_index] #donne le même résultat que
v.take(row_index)

array([2, 4, 8])

In [172]:
M = np.matrix(A)
M

matrix([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])