### NumPy

In [2]:
import numpy as np

In [9]:
A = np.array([[1, 2], [3, 6]])
B = np.array([[2, 1], [4, 3]])

In [14]:
C = A + B
C

array([[3, 3],
       [7, 9]])

In [15]:
D = A - B
D

array([[-1,  1],
       [-1,  3]])

In [17]:
E = A.dot(B)
E

array([[10,  7],
       [30, 21]])

In [18]:
F = A.T
F

array([[1, 3],
       [2, 6]])

In [31]:
G = array([[n + m for n in range(3)] for m in range(3)])
G

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [35]:
H = matrix(G)
H

matrix([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])